[tool.autopep8]
max_line_length = 80
ignore = [
    "E501"
]

[tool.black]
line-length = 80
target-version = ["py38"]
include = '\.py?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | data
  | docs
  | logs
)
'''